// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbFhAiIQ287qooZbPB8pG2R3lAigTGoRo',
    appId: '1:273016929002:web:ca055148e249c990beb593',
    messagingSenderId: '273016929002',
    projectId: 'forsanprinting',
    authDomain: 'forsanprinting.firebaseapp.com',
    storageBucket: 'forsanprinting.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-u22ySWjG8iNeujwFlfeHPUHOiZy2oKo',
    appId: '1:273016929002:android:c7d6556fbead4b00beb593',
    messagingSenderId: '273016929002',
    projectId: 'forsanprinting',
    storageBucket: 'forsanprinting.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVvkOpGNaMETSIgnmp2V81814MwXdjH-Y',
    appId: '1:273016929002:ios:7164b7f60817a07bbeb593',
    messagingSenderId: '273016929002',
    projectId: 'forsanprinting',
    storageBucket: 'forsanprinting.appspot.com',
    iosClientId:
        '273016929002-tkak04np9r6as68hu0nn06cvcj3nigok.apps.googleusercontent.com',
    iosBundleId: 'com.mjd.forsan.forsan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVvkOpGNaMETSIgnmp2V81814MwXdjH-Y',
    appId: '1:273016929002:ios:4f7eb053e3e7083ebeb593',
    messagingSenderId: '273016929002',
    projectId: 'forsanprinting',
    storageBucket: 'forsanprinting.appspot.com',
    iosClientId:
        '273016929002-u19fjd8hd6obkrmd73msf5j9lmpvhs31.apps.googleusercontent.com',
    iosBundleId: 'com.mjd.forsan.forsan.RunnerTests',
  );
}
